#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

# Remove packages
apt-get remove -y --purge --auto-remove transmission-common empathy
apt-get remove -y --purge --auto-remove gnome-getting-started-docs

# Set NHSbuntu banner
rm /usr/share/plymouth/ubuntu-gnome_logo.png
cp /usr/share/plymouth/nhsbuntu-gnome_logo.png /usr/share/plymouth/ubuntu-gnome_logo.png

# Remove Evolution.desktop; provided by nhsmail.desktop
rm /usr/share/applications/evolution.desktop

# Replace LibreOffice startup image
cp /usr/share/nhsbuntu/libreoffice/Flat_LO_and_NHSB_logo.png /usr/lib/libreoffice/program/intro.png

# Replace Ubiquity-slideshow index.html
cp /usr/share/ubiquity-slideshow/slides/extra/en_GB/index.html /usr/share/ubiquity-slideshow/slides/index.html

# Gnome WIndows 10 Theme and icons
cd /usr/share/nhsbuntu/win10-theme
./install.sh

# Add Gnome dash-to-panel extension
cp /usr/share/nhsbuntu/bin/gnome-shell-extension-manage /usr/local/bin/gnome-shell-extension-manage
gnome-shell-extension-manage --install --extension-id 1160 --system
dconf update
